---
openapi: 3.0.2
info:
  title: InnovareMiddleware
  version: 1.0.0
  description: ""
paths:
  /configuration:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConfigurationItem'
          description: Configuration response
      operationId: actualConfiguration
      description: Return the actual configuration.
  /login:
    get:
      parameters:
      - name: username
        description: ""
        schema:
          type: string
        in: query
        required: true
      - name: password
        description: "L'utilizzo del tipo password ha generato errori, \nutilizzo\
          \ per test del tipo string normale"
        schema:
          type: string
        in: query
        required: true
      responses:
        "200":
          description: Login is done correctly.
      operationId: login
  /allsample/{idcanale}:
    get:
      parameters:
      - name: idcanale
        in: path
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sample'
          description: Restituisce tutti i Sample di un dato canale.
      operationId: allsamples
      summary: Restituisce tutti i Sample di un certo canale
      description: Id del canale selezionato.
    parameters:
    - name: idcanale
      in: path
      required: true
  /lastsample/{idcanale}:
    get:
      parameters:
      - name: idcanale
        schema:
          type: string
        in: path
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sample'
          description: Json of the last misure.
      operationId: lastsample
      description: |
        Return json of the last misure.
    parameters:
    - name: idcanale
      in: path
      required: true
  /lastsamples/{idcanale}:
    get:
      parameters:
      - name: idcanale
        schema:
          type: string
        in: path
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sample'
          description: Ultimi Samples del canale che non sono ancora stati visualizzati.
      operationId: lastsamples
      description: Id Channel di riferimento.
  /daysamples/{idcanale}:
    summary: Ritorna i Samples della giornata corrente
    get:
      parameters:
      - name: idcanale
        in: path
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sample'
          description: Samples of the current day.
      operationId: daysamples
    parameters:
    - name: idcanale
      in: path
      required: true
components:
  schemas:
    ConfigurationItem:
      description: Configurazione piattaforma, comprende il gateway e il modello
      required:
      - id
      - properties
      type: object
      properties:
        id:
          description: ""
          type: string
        properties:
          description: ""
          type: array
          items:
            $ref: '#/components/schemas/Property'
      example:
        id: sensor-gateway
        properties:
        - id: indirizzo
          value: 192.168.55.5
        - id: porta
          value: "8888"
    Property:
      description: ""
      required:
      - id
      type: object
      properties:
        id:
          description: ""
          type: string
        value:
          description: ""
          type: string
    User:
      description: ""
      required:
      - username
      - password
      - role
      type: object
      properties:
        username:
          description: ""
          type: string
        password:
          format: password
          description: ""
          type: string
        role:
          description: ""
          enum:
          - USER
          - ADMIN
          type: string
      example:
        password: iUPse124#
        role: ADMIN
        username: administrator
    Sample:
      description: Dato di misurazione di test.
      type: object
      example:
        timestamp: 2020-10-16 16:13:11.781
        misure: 30
        channel: "0"
