---
openapi: 3.0.2
info:
  title: InnovareMiddleware
  version: 1.0.0
  description: |-
    Effettuiamo una nuova classificazione passando il nome del modello
    da voler utilizzare.
paths:
  /configuration:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConfigurationItem'
          description: Configuration response
      operationId: actualConfiguration
      description: Return the actual configuration.
  /login:
    get:
      parameters:
      - name: username
        description: ""
        schema:
          type: string
        in: query
        required: true
      - name: password
        description: "L'utilizzo del tipo password ha generato errori, \nutilizzo\
          \ per test del tipo string normale"
        schema:
          type: string
        in: query
        required: true
      responses:
        "200":
          description: Login is done correctly.
      operationId: login
  /allsample/{idcanale}:
    get:
      parameters:
      - name: idcanale
        in: path
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sample'
          description: Restituisce tutti i Sample di un dato canale.
      operationId: allsamples
      summary: Restituisce tutti i Sample di un certo canale
      description: Id del canale selezionato.
    parameters:
    - name: idcanale
      in: path
      required: true
  /lastsample/{idcanale}:
    get:
      parameters:
      - name: idcanale
        schema:
          type: string
        in: path
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sample'
          description: Json of the last misure.
      operationId: lastsample
      description: |
        Return json of the last misure.
    parameters:
    - name: idcanale
      in: path
      required: true
  /lastsamples/{idcanale}:
    get:
      parameters:
      - name: idcanale
        schema:
          type: string
        in: path
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sample'
          description: Ultimi Samples del canale che non sono ancora stati visualizzati.
      operationId: lastsamples
      description: Id Channel di riferimento.
  /daysamples/{idcanale}:
    summary: Ritorna i Samples della giornata corrente
    get:
      parameters:
      - name: idcanale
        in: path
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sample'
          description: Samples of the current day.
      operationId: daysamples
    parameters:
    - name: idcanale
      in: path
      required: true
  /lastClassification:
    summary: Return the last classification
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Classification'
          description: Json of last classification.
      operationId: lastclassificazion
      summary: Return the last classification
  /newClassification/{modelName}:
    summary: Generete a new classification data.
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Classification'
          description: Classification is done correctly
      operationId: newclassification
      summary: Generete a new classification data.
    parameters:
    - name: modelName
      in: path
      required: true
  /getClassifications/{date}:
    summary: Restituisce tutte le classificazioni di una certa data
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Classification'
          description: Restituisce tutte le classificationi in base alla data
      operationId: getClassificationByDate
    parameters:
    - name: date
      in: path
      required: true
components:
  schemas:
    ConfigurationItem:
      description: "Configurazione piattaforma, comprende il gateway e il modello"
      required:
      - id
      - properties
      type: object
      properties:
        id:
          description: ""
          type: string
        properties:
          description: ""
          type: array
          items:
            $ref: '#/components/schemas/Property'
      example:
        id: sensor-gateway
        properties:
        - id: indirizzo
          value: 192.168.55.5
        - id: porta
          value: "8888"
    Property:
      description: ""
      required:
      - id
      type: object
      properties:
        id:
          description: ""
          type: string
        value:
          description: ""
          type: string
    User:
      description: ""
      required:
      - username
      - password
      - role
      type: object
      properties:
        username:
          description: ""
          type: string
        password:
          format: password
          description: ""
          type: string
        role:
          description: ""
          enum:
          - USER
          - ADMIN
          type: string
      example:
        password: iUPse124#
        role: ADMIN
        username: administrator
    Sample:
      description: Dato di misurazione di test.
      type: object
      example:
        timestamp: 2020-10-16 16:13:11.781
        misure: 30
        channel: "0"
    Classification:
      description: Result of a classification process.
      type: object
      example:
        date: 2020/09/11
        path: /home/stefano/Scrivania/Lavoro/IMMAGINI-TestPythonScript/d3/2020_09_11_Dataset_FondatanaDeiFieri-Thermal_Optical-Fila_3_4-Session1-DJI_0831-plant_1.jpg
        hash: 1ec6cc13769ab7310345101d32509080
        classification:
          classifications:
          - classe: "0"
            score: 23.196931183338165
          - classe: "1"
            score: 23.196931183338165
          - classe: "2"
            score: 23.196931183338165
          - classe: "3"
            score: 23.196931183338165
          - classe: "4"
            score: 23.196931183338165
          hash: '''1ec6cc13769ab7310345101d32509080'''
        originalImage: /home/stefano/Scrivania/Lavoro/IMMAGINI-TestPythonScript/d3/2020_09_11_Dataset_FondatanaDeiFieri-Thermal_Optical-Fila_3_4-Session1-DJI_0831-erased_background_with_boxes.jpg
